name: Secret Switch

on:
  workflow_dispatch:
    inputs:
      direction:
        description: 'Choose direction to turn'
        required: true
        default: 'RIGHT'
        type: choice
        options:
          - 'RIGHT'
          - 'LEFT'

jobs:
  turn-secret:
    runs-on: ubuntu-latest
    env:
      TURN_DIRECTION: ${{ github.event.inputs.direction == 'RIGHT' && secrets.TURN_RIGHT || secrets.TURN_LEFT }}
    steps:
      - name: Print Direction
        run: |
          echo "We are truning: $TURN_DIRECTION"
          echo "The secrets are protected and we should see stars!"
  turn-variable:
    runs-on: ubuntu-latest
    env:
      TURN_DIRECTION: ${{ github.event.inputs.direction == 'RIGHT' && vars.TURN_RIGHT || vars.TURN_LEFT }}
    steps:
      - name: Print Vars Direction
        run: |
          echo "We are turning: $TURN_DIRECTION"
          echo "Variables are ok, we should see where we going"