
name: Secret Switch With Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose enviornment to apply changes'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - PRD 
      region:
        description: 'Choose region to deploy'
        required: true
        default: 'USA'
        type: choice
        options:
          - 'USA'
          - 'EU'

jobs:
  turn-secret:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      DB_HOST: ${{ github.event.inputs.region == 'USA' && vars.DB_HOST_USA || vars.DB_HOST_EU }}
      DB_PASSWORD: ${{ github.event.inputs.region == 'USA' && secrets.DB_PASSWORD_USA || secrets.DB_PASSWORD_EU }}

    steps:
      - name: Print Direction
        run: |
          echo "Database Host to Connect: $DB_HOST"
          echo "Database Password: $DB_PASSWORD"