name: Secret Switch

on:
  workflow_dispatch:
    inputs:
      direction:
        description: 'Choose direction to turn'
        required: true
        default: 'RIGHT'
        type: choice
        options:
          - 'RIGHT'
          - 'LEFT'

jobs:
  turn:
    runs-on: ubuntu-latest
    env:
      TURN_DIRECTION: ${{ github.event.inputs.direction == 'RIGHT' && secrets.TURN_RIGHT || secrets.TURN_LEFT }}
    steps:
      - name: Print Direction
        run: |
          echo "We are truning: $TURN_DIRECTION"